version: "3.5"
networks:
  docker-db-adder:
    name: docker-db-adder
services:
  app:
    build: .
    container_name: docker_db_adder_app
    entrypoint: ["node", "./index.js"]
    environment:
      PORT: 3000
    ports:
    - 3000:3000
  mysql:
    image: mysql:5.7.23
    container_name: docker_db_adder_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
