version: "3.5"
networks:
  db-maker:
    name: db-maker
services:
  app:
    build: .
    container_name: db_maker_app
    entrypoint: ["node", "./index.js"]
    environment:
      PORT: 3000
    ports:
    - 3000:3000
  mysql:
    image: mysql:5.7.23
    container_name: db_maker_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
